services:
  - type: web
    name: plastima-backend
    env: node
    rootDir: backend
    buildCommand: npm install --production
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
